on:
  pull_request_target:
    types: [opened,synchronize]

name: OnSyncPR
jobs:
  check-format:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.author_association == 'COLLABORATOR' || github.event.pull_request.author_association == 'MEMBER' || github.event.pull_request.author_association == 'OWNER'
    steps:
      - name: Checkout the latest code (shallow clone)
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Check for formatting changes
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: echo "${{ github.workflow }}-${{ github.event.pull_request.number }}"
      - name: Upload code formatting patch
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: format.patch
