on:
  push:
    branches:
      - develop
name: CAS-Sync
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        ref: develop
        fetch-depth: 0
    - name: Synchronize with CAS repository
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: .github/cas-sync.sh